Upgrade to Windows SDK 10.0.22000.0
microsoft/react-native-windows pull request #10869
Opened 2022-11-10 02:11 UTC by JunielKatarn

## Description
Upgrade to Windows SDK 10.0.22000.0

### Type of Change
- New feature (non-breaking change which adds functionality)

### Why
ARM64EC requires Windows SDK version 10.0.22000.0 to correctly handle intrinsics includes.
See https://developercommunity.visualstudio.com/t/arm64ec-toolchain-doesnt-work/1460523

Windows SDK 10.0.19041.0 does not ship `softintrin.h`, causing compilation errors on the affected platform.

### What
Replaced references to Windows SDK version 10.0.19041.0 with version 10.0.22000.0.

2022-11-10 02:16 UTC, JunielKatarn commented on packages/@react-native-windows/cli/src/runWindows/utils/build.ts
> +  const minVersion = new Version(10, 0, 22000, 0);
Should we keep `19041` as a minimum version?

2022-11-10 03:19 UTC, JunielKatarn commented on vnext/Scripts/rnw-dependencies.ps1
> +    'Microsoft.VisualStudio.Component.Windows10SDK.22000');
This is failing PR validation.

Do we need to apply an update to the build agent image?

2022-11-10 19:23 UTC, jonthysell requested changes
Please hold on this, it's not as easy (or desirable) to just do a find-replace.

2022-11-10 20:40 UTC, JunielKatarn commented
> Please hold on this, it's not as easy (or desirable) to just do a find-replace.

Sure thing. Reverting to draft for now.

Is there a suggested sequence to carry this type of upgrade?

2022-11-14 19:04 UTC, jonthysell commented
> > Please hold on this, it's not as easy (or desirable) to just do a find-replace.
> 
> Sure thing. Reverting to draft for now.
> 
> Is there a suggested sequence to carry this type of upgrade?

Well, ideally we don't want to upgrade everyone unless there's some clear requirement. Since Desktop needs it, I think it would be easier to simply override the version when building the Desktop and leave UWP to default targeting 19041.

2022-11-14 21:33 UTC, JunielKatarn commented
> Well, ideally we don't want to upgrade everyone unless there's some clear requirement. Since Desktop needs it, I think it would be easier to simply override the version when building the Desktop and leave UWP to default targeting 19041.

That is certainly an option.

I figured it would be convenient to have both variants on the same SDK version.
As stated in the PR description, reducing the installation footprint (VS 2022 defaults to 22000 for the UWP workflow) seemed like a good reason.

Given the min SDK version remains unchanged, what's the criteria to upgrade the target SDK version?
If I read you right, do we prefer to never upgrade unless forced to?

2024-05-30 22:52 UTC, closed without merging