C++20: use view() instead of str() to avoid a copy, use starts_with
microsoft/react-native-windows pull request #13218
Opened 2024-05-11 01:53 UTC by servusdei2018

## Description
Use `view()` instead of `str()`, `starts_with()` instead of `_Starts_with()`.

### Why
Resolves two TODO items

### What

One instance of a `str()` invocation was replaced with `view()`, avoiding an unnecessary copy. Additionally, the private function `_Starts_with()` was replaced with C++20's `starts_with()`.

## Changelog
Should this change be included in the release notes: _no_
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/react-native-windows/pull/13216)

2024-05-11 22:11 UTC, marlenecota commented
@servusdei2018 - please run `yarn format` and push those changes :)

2024-05-12 21:47 UTC, servusdei2018 commented
Hm I tried running `yarn format` but git doesn't register any changes:

```sh
react-native-windows$ yarn format
yarn run v1.22.22
$ format-files -i -style=file


ran clang-format on 1119 files
Done in 3.35s.
react-native-windows$ git status
On branch servusdei2018-patch-1
Your branch is up to date with 'origin/servusdei2018-patch-1'.

nothing to commit, working tree clean
```

2024-05-13 22:28 UTC, jonthysell requested changes

2024-05-13 22:28 UTC, jonthysell commented on change/react-native-windows-f53a2b65-d364-49a5-978c-5d64e08c22ea.json
> +  "type": "none",
```suggestion
  "type": "prerelease",
```

2024-05-13 22:28 UTC, jonthysell commented on change/react-native-windows-f53a2b65-d364-49a5-978c-5d64e08c22ea.json
> +  "dependentChangeType": "none"
```suggestion
  "dependentChangeType": "patch"
```

2024-05-13 22:28 UTC, jonthysell commented on package.json
> -  }
Your change shouldn't need to modify the package.json, please revert.

2024-05-13 23:04 UTC, servusdei2018 commented on package.json
> -  }
Reverted, thank you for the review!

2024-05-14 01:33 UTC, marlenecota approved these changes

2024-05-14 04:39 UTC, merged