Increase the syntaxtoken size to 8 parameters
microsoft/react-native-windows pull request #13477
Opened 2024-07-19 22:01 UTC by sharath2727

## Description

### Type of Change
_Erase all that don't apply._
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update

### Why
Add Method should be able to accept 8 parameters.

Resolves #13307

### What
Increase the size of SyntaxToken to keep in line with ios and android.

## Testing
Pending

## Changelog
yes

Summary: [Pending]

2024-07-22 17:34 UTC, Yajur-Grover requested changes

2024-07-22 17:34 UTC, Yajur-Grover commented on vnext/Microsoft.ReactNative.Managed/packages.lock.json
@chiaramooney do we want to include these lockfile changes in the PR?

2024-07-22 18:13 UTC, chrisglein commented
> Summary: Method effective parameters is updated to support 8 arguments. With this Codegen now generates a method with 8 arguments to keep inline with other platforms.

While we're in here, why not bump it a bit further to future-proof against the next customer ask? Go to 10? [11](https://youtu.be/4xgx4k83zzc?si=NqStGi4ApFWw9Q7E)?

2024-07-23 23:33 UTC, Yajur-Grover approved these changes

2024-07-24 17:25 UTC, merged