[Not ready for review] "vnext" -> "packages/react-native-windows"
microsoft/react-native-windows pull request #7902
Opened 2021-05-30 21:06 UTC by NickGerleman

Just did the mechanical change. No checking yet for anything like relative path escapes. Will need changes to docs site as well.

We are helped that most packages are importing by package name, instead of repo location.

2021-05-30 21:07 UTC, NickGerleman commented on packages/e2e-test-app/windows/ReactUWPTestApp.sln
> +Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "Common", "..\..\..\packages/react-native-windows\Common\Common.vcxproj", "{FCA38F3C-7C73-4C47-BE4E-32F77FA8538D}"
Need to fixup for consistent slash direction

2021-05-31 13:42 UTC, NickGerleman commented on packages/react-native-windows/proposals/active/readme.md
> +This folder contains proposal documents for `react-native-windows @packages/react-native-windows` features that are under active development.
needs fix

2021-05-31 13:44 UTC, NickGerleman commented on packages/react-native-windows/CHANGELOG.json
> -            "comment": "Update vnext/Microsoft.ReactNative.Cxx/README.md",
Need to revert changelog changes

2021-05-31 17:32 UTC, vmoroz commented
It would be preferable that we do not need to go into the deep subfolder to the source files. It is better to use the 'src' folder instead of 'vnext' for the source files. The rest of the Node.js package definition can go into the packages/react-native-windows if needed. Having source files in the 'src' folder is the common open source practice. E.g. see https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/vector-of-bool/pitchfork/develop/data/spec.bs

2021-05-31 17:32 UTC, vmoroz requested changes
:clock1:

2021-05-31 17:48 UTC, NickGerleman commented
Discussing offline, but I do not think such a convention is applicable when this is for existing code inside of a JS monorepo with multiple different packages (with some also having native code).

2021-05-31 17:49 UTC, NickGerleman commented
That sort of structure would make sense inside of an individual package I think.

2021-06-03 16:36 UTC, NickGerleman commented
Closing this pending further discussion.

2021-06-03 16:36 UTC, closed without merging